### ISSUE TITLE
Окно показывается не полностью

### ISSUE THREAD

**Issue by AzimovUA** [WutADude/YTArchiveCollector#1]
Что-то не так с расширением окна из-за чего не вижу кнопки скачать видео.
<details>
<summary>Картинка</summary>
<img src="https://user-images.githubusercontent.com/59807075/205131952-e166a6aa-31d0-48be-a0f2-c4a581780670.png"></details>

Можно пофиксить если дать возможность пользователям растягивать окно.

**Comment by WutADude** [comment]
Попробуй загрузить релиз 2.2, добавил проверку на размеры, если всё сработает как думаю, то софт даст изменять размер окна. Если сработает проверка - в некст релизе просто сделаю авто-добавку высоты к форме при похожей проблеме.
Также вижу, что и текст ещё наезжает... Какое разрешение монитора? Просто подозреваю, что этот костыль никак не поможет т.к. я вообще не занимался адаптивной вёрсткой на формах да и занимается этим почти никто :D
Отпиши сюда о результате :)

**Comment by AzimovUA** [comment]
> Какое разрешение монитора? 

Разрешение 1920x1080, просто в настройках дисплея в винде стоит масштабирование 175%

Новый релиз не помог, растягивать нельзя. 
<details>
<summary>Картинка</summary>
<img src="https://user-images.githubusercontent.com/59807075/205408676-669fc264-6526-4f6c-89f1-21b8cfb0c20f.png"></details>
Впринципе, предпологаю, что с моей стороны это фиксится установкой стандартного масштабирования, но если ты хочешь то можешь попробовать пофиксить)
Спасибо за ответ.
